FROM osrf/ros:kinetic-desktop-full


COPY ./ros_entrypoint.sh /


RUN apt-get update
RUN apt-get install python3-numpy python3-pip libgl1-mesa-glx libgl1-mesa-dri mesa-utils mesa-utils-extra libxv1 va-driver-all  pulseaudio-utils  python-catkin-tools --yes && \
  rm -rf /var/lib/apt/lists/*
RUN pip3 install -U pip
RUN pip3 install -U numpy scipy pandas matplotlib jupyter rospkg

ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

#COPY pulse-client.conf /etc/pulse/client.conf #for audio


# clone ros package repo
ENV ROS_WS /opt/catkin_ws
ENV ROS_DISTRO kinetic
RUN mkdir -p $ROS_WS/src
WORKDIR $ROS_WS



RUN apt-get update -q && \
    apt-get upgrade -yq && \
    apt-get install -yq wget curl git build-essential vim sudo lsb-release locales bash-completion
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu xenial main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -k https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
RUN apt-get update -q && \
    apt-get install -y ros-kinetic-desktop-full &&\
    rm -rf /var/lib/apt/lists/*
RUN rosdep init
RUN locale-gen en_US.UTF-8
RUN useradd -m -d /home/ubuntu ubuntu -p `perl -e 'print crypt("ubuntu", "salt"),"\n"'` && \
    echo "ubuntu ALL=(ALL) ALL" >> /etc/sudoers
USER ubuntu
WORKDIR /home/ubuntu
ENV HOME=/home/ubuntu \
    CATKIN_SHELL=bash
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
RUN rosdep update
RUN mkdir -p ~/catkin_ws/src \
    && /bin/bash -c '. /opt/ros/kinetic/setup.bash; catkin_init_workspace $HOME/catkin_ws/src' \
    && /bin/bash -c '. /opt/ros/kinetic/setup.bash; cd $HOME/catkin_ws; catkin_make'
RUN echo 'source /opt/ros/kinetic/setup.bash' >> ~/.bashrc \
    && echo 'source ~/catkin_ws/devel/setup.bash' >> ~/.bashrc



COPY ipython_robot_prototyping $ROS_WS/src/interactive_robot_prototyping

# install ros package dependencies
#RUN apt-get update && \
#    rosdep update && \
#    rm -rf /var/lib/apt/lists/*

# build ros package source
RUN /bin/bash -c ". /ros_entrypoint.sh; cd /opt/catkin_ws/src ; catkin_init_workspace; cd ..; catkin_make"


#RUN /bin/bash -c '. /opt/ros/kinetic/setup.bash; cd <into the desired folder e.g. ~/catkin_ws/src>; catkin_make'

# source ros package from entrypoint
RUN sed --in-place --expression \
      '$isource "/opt/catkin_ws/devel/setup.bash"' \
      /ros_entrypoint.sh



RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension

RUN cd /opt/catkin_ws/src/interactive_robot_prototyping ; pip3 install -r requirements.txt
    
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]






